export enum ApiService {
    Account = 'account',
    Avatars = 'avatars',
    Databases = 'databases',
    Tables = 'tables',
    Locale = 'locale',
    Health = 'health',
    Storage = 'storage',
    Teams = 'teams',
    Users = 'users',
    Sites = 'sites',
    Functions = 'functions',
    Graphql = 'graphql',
    Messaging = 'messaging',
}