export enum AppwriteMigrationResource {
    User = 'user',
    Team = 'team',
    Membership = 'membership',
    Database = 'database',
    Table = 'table',
    Column = 'column',
    Index = 'index',
    Row = 'row',
    Document = 'document',
    Attribute = 'attribute',
    Collection = 'collection',
    Bucket = 'bucket',
    File = 'file',
    Function = 'function',
    Deployment = 'deployment',
    EnvironmentVariable = 'environment_variable',
    Site = 'site',
    SiteDeployment = 'site_deployment',
    SiteVariable = 'site_variable',
}