export enum UsageEventDimension {
    Path = 'path',
    Method = 'method',
    Status = 'status',
    Service = 'service',
    ResourceType = 'resourceType',
    Country = 'country',
    ContinentCode = 'continentCode',
    City = 'city',
    Region = 'region',
    Hostname = 'hostname',
    Ip = 'ip',
    OsName = 'osName',
    ClientType = 'clientType',
    ClientName = 'clientName',
    DeviceName = 'deviceName',
    Sdk = 'sdk',
    SdkVersion = 'sdkVersion',
    TeamId = 'teamId',
    ResourceId = 'resourceId',
}